version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - boltdb_data:/data
    environment:
      - BOLTDB_PATH=/data/mydb.db

volumes:
  boltdb_data:
